theme: jekyll-theme-tactile
title: Esti Kemp
description: I am a PhD student with AIFMRM, the African Institute of Financial Markets and Risk Management at the University of Cape Town. I am also a Senior Analyst in the Financial Stability Department of the South African Reserve Bank.
