theme: jekyll-theme-slate
title: Esti Kemp

author :
  name : Karl Broman
  email : kbroman@gmail.com
  github : kbroman
  twitter : kwbroman
  feedburner : nil
description: I am a PhD student with AIFMRM, the African Institute of Financial Markets and Risk Management at the University of Cape Town. I am also a Senior Analyst in the Financial Stability Department of the South African Reserve Bank.
#heading test
despription: new line test
